version: 2.1
orbs:
  python: circleci/python@3.2.0
jobs:
  build_and_test:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements.txt
      - run:
          name: Run test
          command: pytest
workflows:
  main:
    jobs:
      - build_and_test